/* This module renders only after the existing parent gate succeeds. */
(() => {
 'use strict';
 const S=window.ELAStore,C=window.ELA_CURRICULUM,e=S.esc;
 const types=['Independent','Directions clarified','Verbal prompting','Organizational help','Spelling help','Scribing/dictation','Other assistance'];
 const ratings={unobserved:'Not observed in this task',developing:'Needs more practice',supported:'Demonstrated with support',independent:'Demonstrated independently',insufficient:'Insufficient evidence / no response'};
 const get=()=>S.read(S.reviewKey,{reviews:{},observations:[],comparison:''});
 function change(fn){const p=get();p.reviews??={};p.observations??=[];fn(p);S.write(S.reviewKey,p);}
 function draft(id,fn){change(p=>{p.reviews[id]??={assistance:[],skills:{}};fn(p.reviews[id]);});}
 function options(value){return '<option value="">Not yet reviewed</option>'+Object.entries(ratings).map(([k,v])=>`<option value="${k}" ${value===k?'selected':''}>${e(v)}</option>`).join('');}
 function baseline(){const b=S.read('roryBaseline2026_writing');return ['writing-25','writing-26','writing-27'].map((id,i)=>{const v=b?.answers?.[id];return {id,genre:['Narrative','Informational','Opinion'][i],status:!b?'No saved writing baseline':v?.text?.trim()?'Written response available':'Insufficient evidence — no written composition',response:v?.text||'',unknown:!!v?.unknown,submittedAt:b?.submittedAt||null};});}
 function render(){
  const host=document.getElementById('ela-parent');if(!host)return;
  const p=get(),works=S.evidence(),releases=S.read(S.prefix+'releases',{}),obs=p.observations||[];
  host.innerHTML=`<h2>Rory’s seven-week writing workshop</h2><p>Build from ideas to complete sentences, connected sentences, organized pieces, revision, and editing. A short independent piece can show valuable growth. Non-responses are insufficient evidence, never automatic zero scores. This local evidence is not a standardized grade, placement decision, or overall mastery score.</p><p>Use mentor texts to teach writing moves. Do not infer a reading deficit from writing evidence. The separate Reading Baseline remains the source for reading follow-up.</p><p>For independent samples, clarify directions only as needed. Do not supply ideas, dictate sentences, organize the response, or correct spelling during composition. Record every kind of assistance that occurred. Browser spelling suggestions are disabled on performance-sample fields.</p><p><a href="${e(C.standardsSource)}" target="_blank" rel="noopener">California Grade 3 standards</a>. Earlier-grade sentence, proper-name/day capitalization, and greeting conventions are labeled as prerequisite review. This is a selected writing/language bridge, not the whole Grade 3 ELA course.</p><div class="actions no-print"><button id="ela-export">Export ELA work and parent observations</button></div>
  <h3>Repeated evidence by skill</h3><p>Counts are dated observations, not grades or mastery claims. Compare task difficulty, assistance, and multiple samples before drawing conclusions.</p><div class="ela-table-wrap"><table class="report-table"><thead><tr><th>Skill</th><th>Independent observations</th><th>Supported</th><th>Needs practice</th><th>Insufficient</th></tr></thead><tbody>${Object.entries(C.skills).map(([id,label])=>{const count=v=>obs.filter(o=>o.skills?.[id]===v).length;return `<tr><td>${e(label)}</td><td>${count('independent')}</td><td>${count('supported')}</td><td>${count('developing')}</td><td>${count('insufficient')}</td></tr>`;}).join('')}</tbody></table></div>
  <h3>New performance prompts</h3><p>Each suggested prompt is different from the original baseline and the practice tasks. Check it against Rory’s actual topics; replace it if it has been rehearsed. Keep the genre and short, familiar-content demand. Release the three Week 7 samples in separate sessions. You can release the next one after the preceding sample is saved, or after recording a non-response observation.</p>
  ${C.assignments.filter(a=>a.release).map(a=>`<details class="panel no-print"><summary>Week ${a.week}.${a.sequence} · ${e(a.title)} · ${releases[a.id]?'Released':'Not released'}</summary>${releases[a.id]?`<div class="ela-response">${e(releases[a.id].prompt)}</div><p>Released ${e(releases[a.id].releasedAt)}. This prompt remains fixed for this attempt.</p>`:`<label>New ${a.title.includes('story')?'narrative':a.title.includes('explanation')?'informational':'opinion'} prompt<textarea id="prompt-${a.id}" rows="4">${e(window.ELA_PARENT_PROMPTS[a.id])}</textarea></label><label class="ela-check"><input type="checkbox" id="novel-${a.id}">I confirm that this prompt is new and not rehearsed, and this is a separate performance session.</label><button class="button" data-release="${a.id}">Release this prompt</button>`}<p id="release-status-${a.id}" role="status"></p></details>`).join('')}
  <h3>Record an observation without changing Rory’s words</h3><p>Choose the checkpoint you observed. Record support types and only the skills this task shows. “Save dated observation” adds a new entry; earlier observations remain. A repeated successful response is evidence to consider, not automatic mastery.</p>
  ${C.assignments.map(a=>{const w=works[a.id],d=p.reviews?.[a.id]||{},history=obs.filter(o=>o.assignmentId===a.id);return `<details class="panel ela-evidence" data-review="${a.id}"><summary>Week ${a.week}.${a.sequence} · ${e(a.title)} · ${w?.complete?'Complete':w?'In progress':'Not started'}</summary><p>${e(a.kind)} · CA ${e(a.standards.join(', '))}</p>${a.prerequisite?`<p>${e(a.prerequisite)}</p>`:''}<div class="no-print"><label>Observation date<input type="date" data-id="${a.id}" data-meta="date" value="${e(d.date||new Date().toISOString().slice(0,10))}"></label><label>Work observed<select data-id="${a.id}" data-meta="snapshotId"><option value="current">Current saved work</option>${(w?.snapshots||[]).map(s=>`<option value="${e(s.id)}" ${d.snapshotId===s.id?'selected':''}>${e(s.label)} · ${e(s.at)}</option>`).join('')}</select></label><label>Response status<select data-id="${a.id}" data-meta="responseStatus"><option value="observed">Written work observed</option><option value="no-response" ${d.responseStatus==='no-response'?'selected':''}>No response — insufficient evidence</option></select></label><fieldset><legend>Assistance actually provided</legend>${types.map(t=>`<label class="ela-check"><input type="checkbox" data-assist="${a.id}" value="${e(t)}" ${(d.assistance||[]).includes(t)?'checked':''}>${e(t)}</label>`).join('')}</fieldset><div class="ela-rubric">${a.skills.map(id=>`<label>${e(C.skills[id])}<select data-id="${a.id}" data-skill="${id}">${options(d.skills?.[id])}</select></label>`).join('')}</div><label>Comments — help given, evidence, next step<textarea data-id="${a.id}" data-meta="comments" rows="3">${e(d.comments||'')}</textarea></label><button class="button" data-observe="${a.id}">Save dated observation</button></div><p class="ela-review-status" role="status"></p>
  <details><summary>Student work and saved checkpoints</summary>${w?.prompt?`<h4>Prompt</h4><p class="ela-response">${e(w.prompt)}</p>`:''}${w?a.fields.map(f=>`<h4>${e(f.label)}</h4><div class="ela-response">${e(w.fields[f.id]||'(No written response)')}</div>`).join(''):'<p>No saved response; insufficient evidence.</p>'}${(w?.snapshots||[]).map(s=>`<details><summary>${e(s.label)} · ${e(s.at)}</summary>${Object.entries(s.fields).map(([id,v])=>`<h4>${e(a.fields.find(f=>f.id===id)?.label||id)}</h4><div class="ela-response">${e(v)}</div>`).join('')}</details>`).join('')}</details><details><summary>Dated observations (${history.length})</summary>${history.map(o=>`<h4>${e(o.date)} · ${o.responseStatus==='no-response'?'No response — insufficient evidence':'Work observed'}</h4><p>Assistance: ${e(o.assistance.join('; '))}</p><p>${Object.entries(o.skills).map(([id,r])=>e(C.skills[id])+': '+e(ratings[r]||'Not reviewed')).join('<br>')}</p><p class="ela-response">${e(o.comments)}</p><p>Observed version: ${e(o.snapshotLabel)} · ${e(o.savedAt)}</p>`).join('')}</details></details>`;}).join('')}
  <h3>Baseline and final samples</h3><p>Compare available evidence without turning non-responses into failures. Record what changed, which supports were used, and what still needs confirmation. No overall score is calculated.</p>${baseline().map((b,i)=>{const finalId=['ela3-w7-3','ela3-w7-4','ela3-w7-5'][i],w=works[finalId];return `<details class="panel"><summary>${e(b.genre)} comparison</summary><h4>Original baseline</h4><p>${e(b.status)}</p><div class="ela-response">${e(b.response)}</div><h4>New final sample</h4><p>${w?.complete?'Saved sample available':'No completed final sample yet — insufficient evidence'}</p><p>${e(w?.prompt||'')}</p><div class="ela-response">${e(w?.fields.f3||'')}</div></details>`;}).join('')}<label class="no-print">Parent comparison and next instructional steps<textarea id="ela-comparison" rows="5">${e(p.comparison||'')}</textarea></label><p class="ela-response">${e(p.comparison||'No comparison recorded.')}</p><p id="comparison-status" role="status"></p>`;
  function fail(el,error){el.closest('[data-review]').querySelector('.ela-review-status').textContent='NOT SAVED: '+error.message;}
  host.querySelectorAll('[data-meta],[data-skill]').forEach(el=>el.addEventListener(el.tagName==='TEXTAREA'?'input':'change',()=>{try{draft(el.dataset.id,d=>{if(el.dataset.skill){d.skills??={};d.skills[el.dataset.skill]=el.value;}else d[el.dataset.meta]=el.value;});el.closest('[data-review]').querySelector('.ela-review-status').textContent='Review draft saved. Save a dated observation to add it to the skill record.';}catch(error){fail(el,error);}}));
  host.querySelectorAll('[data-assist]').forEach(el=>el.onchange=()=>{try{const group=[...host.querySelectorAll(`[data-assist="${el.dataset.assist}"]`)];if(el.checked)group.forEach(x=>{if(x!==el&&(el.value==='Independent'||x.value==='Independent'))x.checked=false;});draft(el.dataset.assist,d=>{d.assistance=group.filter(x=>x.checked).map(x=>x.value);});el.closest('[data-review]').querySelector('.ela-review-status').textContent='Assistance draft saved; student words unchanged.';}catch(error){fail(el,error);}});
  host.querySelectorAll('[data-observe]').forEach(el=>el.onclick=()=>{try{const a=C.assignments.find(x=>x.id===el.dataset.observe),d=get().reviews?.[a.id]||{},w=S.work(a.id),box=el.closest('[data-review]'),status=box.querySelector('.ela-review-status');if(!d.assistance?.length){status.textContent='Record the assistance provided, including Independent when appropriate.';return;}const date=box.querySelector('[data-meta="date"]').value;if(!date){status.textContent='Choose an observation date.';return;}const selected=box.querySelector('[data-meta="snapshotId"]').value,ss=w.snapshots.find(s=>s.id===selected);const statusValue=box.querySelector('[data-meta="responseStatus"]').value;if(statusValue!=='no-response'&&!Object.values(ss?.fields||w.fields).some(v=>String(v).trim())){status.textContent='No written response is saved. Use No response — insufficient evidence if that is what you observed.';return;}const values=statusValue==='no-response'?Object.fromEntries(a.skills.map(id=>[id,'insufficient'])):{...d.skills};change(p=>{p.observations.push({id:crypto.randomUUID(),assignmentId:a.id,date,savedAt:new Date().toISOString(),responseStatus:statusValue,assistance:[...d.assistance],skills:values,comments:d.comments||'',snapshotId:ss?.id||null,snapshotLabel:ss?.label||'Current work at observation time',observedFields:structuredClone(ss?.fields||w.fields),standards:a.standards});});render();const updated=host.querySelector(`[data-review="${a.id}"]`);updated.open=true;updated.querySelector('.ela-review-status').textContent='Dated observation saved. Original student response was not changed.';}catch(error){fail(el,error);}});
  host.querySelectorAll('[data-release]').forEach(el=>el.onclick=()=>{const id=el.dataset.release,a=C.assignments.find(x=>x.id===id),status=document.getElementById('release-status-'+id);try{const prompt=document.getElementById('prompt-'+id).value.trim();if(!prompt||!document.getElementById('novel-'+id).checked){status.textContent='Enter the prompt and confirm novelty and a separate session.';return;}if(a.week===7&&a.sequence>3){const previous='ela3-w7-'+(a.sequence-1);if(!S.work(previous).complete&&!get().observations?.some(o=>o.assignmentId===previous&&o.responseStatus==='no-response')){status.textContent='Complete or record insufficient evidence for the preceding final sample first.';return;}}const rs=S.read(S.prefix+'releases',{});rs[id]={prompt,releasedAt:new Date().toISOString()};S.write(S.prefix+'releases',rs);render();}catch(error){status.textContent='Prompt NOT saved: '+error.message;}});
  document.getElementById('ela-comparison').oninput=event=>{try{change(p=>{p.comparison=event.target.value;});document.getElementById('comparison-status').textContent='Comparison saved.';}catch(error){document.getElementById('comparison-status').textContent='NOT SAVED: '+error.message;}};
  document.getElementById('ela-export').onclick=()=>S.download('rory-ela-evidence-and-review.json',{schemaVersion:1,student:'Rory',schoolYear:C.schoolYear,exportedAt:new Date().toISOString(),curriculum:C,...backup()});
 }
 function backup(){return {elaEvidence:S.evidence(),elaParent:get(),elaReleases:S.read(S.prefix+'releases',{}),elaBaselineComparison:baseline()};}
 function restore(v){
  S.merge(v.elaEvidence);
  if(v.elaParent){const current=get();current.reviews={...v.elaParent.reviews,...current.reviews};current.observations??=[];const ids=new Set(current.observations.map(o=>o.id));for(const o of v.elaParent.observations||[])if(!ids.has(o.id)){current.observations.push(o);ids.add(o.id);}current.comparison=current.comparison||v.elaParent.comparison||'';S.write(S.reviewKey,current);}
  if(v.elaReleases)S.write(S.prefix+'releases',{...v.elaReleases,...S.read(S.prefix+'releases',{})});
 }
 window.ELAParent={render,backup,restore};
})();
