/* Seven-week Grade 3 History–Social Science course. The completed baseline is never read or changed here. */
window.HISTORY_COURSE = {
  version: "2026.1",
  schoolYear: "2026–2027",
  student: "Rory",
  grade: 3,
  title: "Community Explorer: Maps, Evidence & Place",
  opening: "Welcome, Rory! For seven weeks, you will work like a mapmaker, historian, community helper, and detective. You will move map pieces, arrange timelines, inspect clues, solve community problems, and build a final travel case about Massachusetts and California. You do not need to know every answer before you begin. Your job is to look closely, use evidence, and explain your thinking.",
  routine: ["LOOK CLOSELY", "RECORD A CLUE", "CHECK A SOURCE", "EXPLAIN YOUR IDEA"],
  sources: [
    {title:"California Grade 3 History–Social Science Standards",url:"https://www.cde.ca.gov/be/st/SS/documents/histsocscistnd.pdf"},
    {title:"California History–Social Science Framework, Grade Three",url:"https://www.cde.ca.gov/ci/hs/cf/documents/hssfwchapter6.pdf"},
    {title:"Library of Congress Primary Source Guides",url:"https://www.loc.gov/programs/teachers/getting-started-with-primary-sources/guides/"},
    {title:"Falmouth: Understanding Town Meeting",url:"https://www.falmouthma.gov/533/Understanding-Town-Meeting"},
    {title:"Redding City Council",url:"https://files.cityofredding.gov/government/departments/city_council/index.php"},
    {title:"Mashpee Wampanoag Tribe",url:"https://mashpeewampanoagtribe-nsn.gov/"},
    {title:"Wampanoag Tribe of Gay Head (Aquinnah)",url:"https://wampanoagtribe-nsn.gov/wampanoag-history"},
    {title:"Redding Rancheria",url:"https://www.reddingrancheria-nsn.gov/"},
    {title:"Redding Rancheria — Our Tribes",url:"https://www.reddingrancheria-nsn.gov/our-tribes/"}
  ],
  weeks: [
    {
      id:"history3-w1",week:1,title:"Maps: Massachusetts to California",subtitle:"Directions, keys, scale, and the move west",scope:"Mapmaker week",visual:"map",standards:["K–5 Spatial Thinking 4","HSS 3.1"],
      baselineNote:"This week gathers fresh evidence about map scale and California geography during instruction. It is not a retest or remediation label.",
      lesson:["A map is a small picture of a place. A compass rose shows direction. A map key explains symbols. A scale tells how a map distance matches a real distance. Mapmakers check these tools before making a claim.","Massachusetts is east of California. California is west of Massachusetts. The Atlantic Ocean is east of Massachusetts, and the Pacific Ocean is west of California."],
      vocabulary:[["Map","A drawing that shows where places are."],["Compass rose","A map tool that shows directions."],["Key","A guide that explains map symbols."],["Scale","A rule that compares map distance with real distance."],["Relative location","Where one place is compared with another."],["Route","A path from one place to another."]],
      prep:{label:"PARENT PREP",materials:["Coins or buttons as map markers","Paper, pencil, crayons, and ruler","Optional printed outline map of the United States"],note:"Read the directions aloud if helpful. The maps on this page are simplified learning maps and are not drawn to exact geographic scale."},
      investigations:[{title:"Move through Pine Street",question:"How can map tools prove where a place is?",steps:["Put a marker on Home in the grid.","Move east to School, then east to Library.","Name what is north and south of School.","Make a key with a symbol for Home, School, Library, and Park."],checks:[["map-grid","I moved a marker and made a map key."]],fields:[{id:"libraryDirection",label:"The Library is which direction from the School?",required:true},{id:"mapEvidence",label:"What part of the map proves your answer?",rows:2,required:true},{id:"mapKey",label:"Describe one symbol in your key and what it means.",rows:2,required:true}]},{title:"Scale walk",question:"If one map space equals two blocks, how far is a four-space trip?",steps:["Predict the distance.","Move a counter four spaces on a paper road.","Add 2 + 2 + 2 + 2.","Try a two-space or five-space trip."],checks:[["scale-walk","I used the same scale for at least two trips."]],fields:[{id:"scalePrediction",label:"My prediction",required:true},{id:"scaleResult",label:"Four spaces equals how many blocks? Show or explain your thinking.",rows:2,required:true}]}],
      assignment:{title:"Map the move west",directions:["Mark Massachusetts and California on an outline map.","Label the Atlantic and Pacific Oceans.","Draw an arrow from Massachusetts toward California and add a key.","Use direction words to explain the move."],fields:[{id:"moveMap",label:"Describe or link my completed move map",rows:3,required:true},{id:"relativeSentence",label:"California is ___ of Massachusetts, and the ocean beside California is the ___ Ocean.",rows:2,required:true},{id:"scaleEvidence",label:"How did the scale prove your four-space answer?",rows:2,required:true}]},
      exit:[{id:"check1",prompt:"A path is five spaces long and one space equals two blocks. How long is the path?",type:"select",options:["5 blocks","7 blocks","10 blocks"],required:true},{id:"check2",prompt:"Which map tool explains what a star means?",type:"select",options:["Map key","Compass direction","Date"],required:true},{id:"check3",prompt:"Name one piece of map evidence you used this week.",rows:2,required:true}],
      reviewSkills:["Using a map scale","Locating California and the Pacific Ocean","Explaining with map evidence"],portfolio:"Completed Massachusetts-to-California move map with key, directions, and scale reasoning."
    },
    {
      id:"history3-w2",week:2,title:"Timelines & Historical Evidence",subtitle:"Dates, sources, and clues about the past",scope:"Historian week",visual:"timeline",standards:["K–5 Chronological Thinking 1","K–5 Research, Evidence and Point of View 1–3","HSS 3.3"],
      baselineNote:"This week gathers fresh evidence about timeline order and comparing sources. The mysteries are fictional so you can focus on the thinking skill.",
      lesson:["Historians put events in chronological order, from earlier to later. Dates help us decide what happened before, after, or between other events.","A source is something that gives information about the past, such as a dated photograph, map, letter, interview, artifact, or record. When sources disagree, historians compare them with other relevant evidence."],
      vocabulary:[["Chronological order","Events arranged from earlier to later."],["Timeline","A line that shows events in time order."],["Source","Something that gives information."],["Primary source","Evidence made during the time being studied."],["Artifact","An object made or used by people."],["Claim","An idea supported by evidence."]],
      prep:{label:"PARENT PREP",materials:["Four small paper timeline cards","Pencil and optional sticky notes","Optional familiar object to discuss as an artifact"],note:"Cut or copy these dates onto cards: 2013 garden site chosen; 2015 beds built; 2018 rain barrel added; 2024 new path opened."},
      investigations:[{title:"Put history in order",question:"Where does a new event belong on a timeline?",steps:["Arrange the four event cards from earliest to latest.","Name the event after 2015 and the one between 2013 and 2018.","Add a card for 2016: Garden sign installed.","Use its date to explain where it belongs."],checks:[["timeline-cards","I arranged and checked all five dated cards."]],fields:[{id:"timelineOrder",label:"Write the years in chronological order.",required:true},{id:"betweenEvent",label:"Which event belongs between 2015 and 2018? How do the dates prove it?",rows:2,required:true}]},{title:"Juniper Junction clock mystery",question:"When was the town clock probably added?",steps:["Source A: a 1988 photo shows no clock.","Source B: a 1992 bulletin announces a clock dedication.","Source C: a 2005 map labels the Town Clock.","Record one fact from each source, then make a supported claim."],checks:[["source-case","I inspected all three fictional sources."]],fields:[{id:"sourceFacts",label:"One fact from each source",rows:3,required:true},{id:"clockClaim",label:"I think the clock was added ___ because Source ___ shows ___.",rows:3,required:true}]}],
      assignment:{title:"When two accounts disagree",directions:["Mina remembers that a footbridge opened before a playground. Eli remembers the playground opened first.","A dated record says: Playground opening — May 2007; Footbridge opening — October 2009.","Decide which account the record supports and name another source you could check."],fields:[{id:"accountClaim",label:"Which account does the dated record support?",rows:2,required:true},{id:"accountEvidence",label:"Which dates are the evidence?",rows:2,required:true},{id:"otherSource",label:"What other relevant source could help? Why?",rows:2,required:true}]},
      exit:[{id:"check1",prompt:"Which year is between 2011 and 2019?",type:"select",options:["2009","2015","2022"],required:true},{id:"check2",prompt:"Which source best shows how a building looked in 1970?",type:"select",options:["A dated 1970 photograph","A confident guess","A weather prediction"],required:true},{id:"check3",prompt:"If two memories disagree, what should a historian do?",rows:2,required:true}],
      reviewSkills:["Timeline sequencing","Comparing conflicting accounts","Supporting a historical claim"],portfolio:"Community History Case File with the timeline, clock mystery, and account comparison."
    },
    {
      id:"history3-w3",week:3,title:"Culture, Traditions & Migration",subtitle:"What people pass on and carry to new places",scope:"Culture explorer week",visual:"culture",standards:["HSS 3.3.1"],
      baselineNote:"This week gathers new work evidence about recognizing traditions. You may use fictional or public examples; you never have to share a private family story.",
      lesson:["Culture means shared ways that groups of people understand, express, and organize life. It can include languages, stories, celebrations, music, food, art, knowledge, and ways of helping.","A tradition is meaningful and is passed between generations. A routine can repeat without being a tradition. Migration means moving to live in another place; people may carry language, stories, knowledge, recipes, music, and celebrations with them."],
      vocabulary:[["Culture","Shared ways a group understands and expresses life."],["Tradition","A meaningful practice passed between generations."],["Generation","People born around the same part of time."],["Routine","Something done regularly."],["Migration","Moving to live in a different place."],["Voluntary","Chosen freely."],["Forced migration","Moving because staying is unsafe or not possible."]],
      prep:{label:"PARENT PREP",materials:["Six paper sorting cards","Three-frame drawing paper","A paper bag or drawn suitcase"],note:"Rory may choose fictional examples. Do not require private family or migration details."},
      investigations:[{title:"Tradition or something else?",question:"What makes a tradition different from a routine or measured fact?",steps:["Sort: an older relative teaches a song; a yearly celebration teaches children how it is done; the bus comes at 8; heavy rain falls; a thermometer reads 62°; a family teaches an older recipe.","Use the groups Tradition, Routine, and Weather or Measured Fact.","Choose one card and explain the clue that decided its group."],checks:[["tradition-sort","I sorted all six examples."]],fields:[{id:"traditionSort",label:"Which examples are traditions?",rows:2,required:true},{id:"traditionClue",label:"What detail makes a tradition different from a routine?",rows:2,required:true}]},{title:"Why people move",question:"How can we classify a move from the evidence in a scenario?",steps:["Sort four cases: permanent move for a job; leaving because fighting makes home unsafe; permanent move near relatives; two-day beach visit.","Label each voluntary migration, safety-related migration, or travel.","Put three things people can carry without packing them into a paper suitcase."],checks:[["migration-sort","I sorted all four moves and filled the paper suitcase."]],fields:[{id:"migrationEvidence",label:"Choose one scenario. Which words helped you classify it?",rows:3,required:true},{id:"cultureSuitcase",label:"Three parts of culture that can travel with people",rows:2,required:true}]}],
      assignment:{title:"A tradition travels through time",directions:["Draw three frames: someone learns a tradition; that person shares it later; a younger person continues or adapts it.","Use an imaginary family, story, public community tradition, or nonprivate real example.","Explain why it is a tradition."],fields:[{id:"traditionModel",label:"Describe or link my three-frame model",rows:3,required:true},{id:"traditionClaim",label:"This is a tradition because…",rows:3,required:true},{id:"migrationConnection",label:"How could this tradition travel if people move?",rows:2,required:true}]},
      exit:[{id:"check1",prompt:"Is every routine a tradition?",type:"select",options:["Yes","No"],required:true},{id:"check2",prompt:"A family permanently moves to reach safety. Is this a vacation?",type:"select",options:["Yes","No — it is safety-related migration"],required:true},{id:"check3",prompt:"Name one way culture can travel with people.",rows:2,required:true}],
      reviewSkills:["Recognizing a tradition","Classifying reasons for migration","Explaining cultural continuity"],portfolio:"Three-frame tradition model and culture suitcase."
    },
    {
      id:"history3-w4",week:4,title:"Local Government & Civic Life",subtitle:"Services, community problems, and lawmaking",scope:"Community helper week",visual:"civic",standards:["HSS 3.4.1","HSS 3.4.2","HSS 3.4.4","HSS 3.4.5"],
      baselineNote:"Matching local services is observed during instruction. The role of a legislature is new Grade 3 learning.",
      lesson:["Communities share roads, parks, libraries, and safety needs. Local government organizes many public services. A community detective asks whether a problem is a shared public need and which service could help.","A legislature discusses and votes on proposed laws. In California, the Legislature has a Senate and an Assembly. A state bill that passes both goes to the Governor, who may sign or veto it. Local governments can be organized in different ways."],
      vocabulary:[["Government","A system people use to make and carry out public decisions."],["Public service","Work organized to meet a shared community need."],["Citizen","A legal member of a country who has rights and responsibilities."],["Legislature","A group whose work includes making laws."],["Law","An official rule made by government."],["Evidence","Information that supports an idea or request."]],
      prep:{label:"PARENT-LED ACTIVITY",materials:["Service cards or sticky notes","Five paper lawmaking cards","Pencil and twelve small counters"],note:"Use the fictional crossing problem. Explain that residents bring evidence to the proper authority and do not alter public roads themselves."},
      investigations:[{title:"Who helps with this?",question:"Which public service fits each shared need?",steps:["Match: pothole—public works; broken park swing—parks; books and research—library; building fire—fire department.","Place toys on a bedroom floor under household responsibility.","Choose one match and explain why it fits."],checks:[["service-sort","I matched all five situations."]],fields:[{id:"serviceMatch",label:"Choose one public problem and the service that could help.",rows:2,required:true},{id:"serviceEvidence",label:"Which detail shows this is a shared public need?",rows:2,required:true}]},{title:"Brook Lane crossing problem",question:"How should residents use observations to propose a solution?",steps:["Read: During ten minutes, 12 people crossed near the bus stop. Five cars did not slow.","Circle the measured data.","Choose or draw a marked crossing, warning sign, traffic study, or another reasonable proposal.","Decide which local office residents could contact."],checks:[["civic-case","I used the measured crossing data."]],fields:[{id:"crossingProblem",label:"State the community problem.",rows:2,required:true},{id:"crossingPlan",label:"The community should consider ___ because the evidence shows ___.",rows:3,required:true}]}],
      assignment:{title:"Model how an idea may become a law",directions:["Arrange: people raise a concern; evidence is gathered; an idea is written; the legislature discusses it; members vote.","Hold a family mock vote on a fictional park proposal.","State a reason and one piece of evidence before voting."],fields:[{id:"lawOrder",label:"Write the five steps in order.",rows:3,required:true},{id:"voteReason",label:"My vote, reason, and evidence",rows:3,required:true},{id:"governmentCompare",label:"What is one way residents can participate in a public decision?",rows:2,required:true}]},
      exit:[{id:"check1",prompt:"Who may repair a pothole on a public road?",type:"select",options:["Public works or roads service","A random driver","The weather reporter"],required:true},{id:"check2",prompt:"Which group discusses and votes on proposed laws?",type:"select",options:["A legislature","A sports team","A map key"],required:true},{id:"check3",prompt:"Choose one local service and explain how it helps the community.",rows:2,required:true}],
      reviewSkills:["Matching public needs to services","Using evidence in civic action","Understanding the legislature’s basic role"],portfolio:"One-page Brook Lane community proposal with evidence."
    },
    {
      id:"history3-w5",week:5,title:"Indigenous Peoples, Community & Place",subtitle:"Distinct communities, continuing histories, and reliable sources",scope:"Respectful source week",visual:"indigenous",standards:["HSS 3.2.1–3.2.4","HSS 3.4.5"],
      baselineNote:"This is new Grade 3 instruction. Specific community facts must come from that community or another reliable, identified source.",
      lesson:["Long before Massachusetts and California were states, different Indigenous peoples lived in these places. Indigenous communities continue today as families, cultures, communities, and governments.","Different peoples have distinct histories and relationships to place. Modern state borders do not make all Indigenous peoples one group. A map alone cannot prove what every community did. We check tribe-authored or other reliable sources before making a specific claim."],
      vocabulary:[["Indigenous","The first peoples of a place and their descendants."],["Distinct","Different and having its own identity."],["Sovereign","Having authority to govern itself."],["Community","People connected by place, identity, or shared life."],["Continuity","Something that continues through time."],["Reliable source","A source we can trust for the claim being made."],["Attribution","Naming where information came from."]],
      prep:{label:"REQUIRED PARENT-LED SOURCE LAB",materials:["A parent-selected official Indigenous community webpage","Paper for a Past and Present panel","Optional printed coast, river valley, and forested hills cards"],note:"Record the organization, page title, and URL. Do not invent ceremonies, beliefs, quotations, vocabulary, or homeland boundaries. Official links are listed at the bottom of the course and in the parent guide."},
      investigations:[{title:"Peoples, places, and continuing histories",question:"Which statements respect the evidence?",steps:["Sort these ideas as accurate or inaccurate: Indigenous communities exist only in the past; different peoples have distinct histories; communities continue today; every Indigenous people has one culture; modern state lines are older than all Indigenous homelands.","Correct each inaccurate statement.","Draw a Long Ago → Today → Continuing line."],checks:[["continuity-sort","I sorted and corrected all five statements."]],fields:[{id:"continuityCorrections",label:"Correct two inaccurate statements.",rows:3,required:true},{id:"continuityEvidence",label:"What kind of present-day evidence could show that a Native nation continues today?",rows:3,required:true}]},{title:"Geography gives clues, not a complete story",question:"What can a map support, and what still needs another source?",steps:["Inspect generic coast, river valley, and forested hills cards.","List observable features and resources that could be available.","Make one careful idea using may or could.","Explain why the card cannot prove that every community made the same choice."],checks:[["place-clues","I separated a visible map clue from an idea that needs another source."]],fields:[{id:"placeObservation",label:"One geographic feature I directly observed",rows:2,required:true},{id:"placeIdea",label:"My careful may/could idea and the feature that supports it",rows:3,required:true}]}],
      assignment:{title:"Parent-led local source lab",directions:["Use an official community source connected to Massachusetts, Northern California, or both.","Copy the community or Nation name exactly as the source gives it.","Find one statement about place and one sign of a present-day community.","Make a two-panel Long Ago / Today response with clear attribution."],fields:[{id:"nationName",label:"Community or Nation name exactly as the source gives it",required:true},{id:"sourceOrganization",label:"Source organization and page title",rows:2,required:true},{id:"sourceUrl",label:"Source URL or publication details",required:true},{id:"placeConnection",label:"One source-supported statement about connection to place",rows:3,required:true},{id:"presentEvidence",label:"One source-supported sign that the community continues today",rows:3,required:true},{id:"sourceClaim",label:"I learned ___, and the source showed ___.",rows:3,required:true}]},
      exit:[{id:"check1",prompt:"Are Indigenous peoples only people from long ago?",type:"select",options:["Yes","No — Indigenous communities continue today"],required:true},{id:"check2",prompt:"Did all Indigenous peoples share one identical culture?",type:"select",options:["Yes","No — peoples are distinct"],required:true},{id:"check3",prompt:"What should you check before making a claim about a particular community?",rows:2,required:true}],
      reviewSkills:["Recognizing distinct and continuing Indigenous communities","Using present-day evidence","Attributing a specific claim to a reliable source"],portfolio:"Past-and-present continuity panel and attributed local source record."
    },
    {
      id:"history3-w6",week:6,title:"Geography, Resources & Economics",subtitle:"How places, work, goods, services, and trade connect",scope:"Economics investigator week",visual:"economics",standards:["HSS 3.1.1–3.1.2","HSS 3.5.1–3.5.3"],
      baselineNote:"This week extends Rory’s demonstrated economics strength by connecting it to geography and evidence.",
      lesson:["A resource is something people can use. A good is an object people make, grow, or sell. A service is useful work someone does. Jobs, goods, services, and trade connect communities.","Geography creates opportunities and challenges. A map can support a careful may or could idea, but it does not prove what every person does."],
      vocabulary:[["Resource","Something useful that people can use."],["Good","An object that is made, grown, or sold."],["Service","Useful work done for someone."],["Trade","Exchanging goods or services."],["Scarcity","When there is not enough of something wanted."],["Interdependence","Depending on one another."],["Adapt","Change a plan to fit a situation."]],
      prep:{label:"PARENT PREP",materials:["Resource, job, good, and service cards","A few tokens for trading","Paper for two fictional community maps"],note:"The two communities are fictional. Encourage Rory to cite only features actually shown on each map."},
      investigations:[{title:"Compare two communities",question:"How could geography affect work and community choices?",steps:["Map A, Seabird Bay: coast, harbor, windy shore, road.","Map B, Cedar Crossing: inland river, farms, wooded hills, road.","Name two differences and one similarity.","Suggest one possible job or adaptation in each place and cite a map feature."],checks:[["community-maps","I compared both fictional maps."]],fields:[{id:"mapComparison",label:"Two differences and one similarity",rows:3,required:true},{id:"possibleJobs",label:"A possible job in each place",rows:2,required:true},{id:"geographyEvidence",label:"I think ___ could happen because the map shows ___.",rows:3,required:true}]},{title:"Trading neighbors",question:"How can two communities benefit from exchange?",steps:["Seabird Bay has extra fish. Cedar Crossing has extra apples.","Use tokens to propose a fair exchange.","Draw arrows to show how each depends on the other.","A road closes for a week. Predict one effect and suggest a response."],checks:[["trade-game","I completed a trade and the closed-road challenge."]],fields:[{id:"fairTrade",label:"My fair exchange and how both communities benefit",rows:3,required:true},{id:"roadEffect",label:"One effect of the road closing and a possible response",rows:3,required:true}]}],
      assignment:{title:"Build resource chains",directions:["Arrange at least two resource → job → good/service chains.","Create one original chain.","Show how the same resource could connect to more than one job or product."],fields:[{id:"resourceChains",label:"My two resource chains",rows:3,required:true},{id:"originalChain",label:"My original chain and explanation",rows:3,required:true},{id:"multipleUses",label:"One resource with more than one possible use",rows:2,required:true}]},
      exit:[{id:"check1",prompt:"Which statement is map evidence?",type:"select",options:["The map shows a harbor.","Everyone loves fishing.","This must be the best town."],required:true},{id:"check2",prompt:"Why can trade help two communities?",rows:2,required:true},{id:"check3",prompt:"Name one way geography could affect a community and cite the map evidence.",rows:3,required:true}],
      reviewSkills:["Connecting resources, jobs, goods, and services","Explaining interdependence","Using geography as evidence"],portfolio:"Two-community comparison, resource chains, and trade diagram."
    },
    {
      id:"history3-w7",week:7,title:"Community Detective: Falmouth to Redding",subtitle:"An evidence board that connects the whole course",scope:"Culminating project week",visual:"detective",standards:["Integrated HSS 3.1–3.5","K–5 Analysis Skills"],
      baselineNote:"This project collects integrated work evidence. It is not a placement test or percentage score.",
      lesson:["Community detectives use maps, dates, sources, civic ideas, culture, and economics together. Strong detectives separate what they notice from what they infer and name the evidence behind a claim.","Your final case can be an accordion folder, digital detective board, or six-page field notebook. You will give a short explanation instead of writing a long report."],
      vocabulary:[["Investigation","A careful search for an answer."],["Observation","Something directly noticed in a source."],["Inference","An idea based on observations."],["Corroborate","Check an idea with another source."],["Civic","Connected to community rights and responsibilities."],["Synthesis","Putting ideas together to form a fuller explanation."],["Citation","Information that identifies a source."]],
      prep:{label:"PARENT PREP + PRESENTATION",materials:["Simplified U.S. locator map","One verified dated photo or map for Falmouth and one for Redding, with source details","Paper, colored pencils, scissors, glue, ruler, and optional string"],note:"Use a fictional inset route for the scale problem. Any specific Indigenous community information must use the verified Week 5 source process."},
      investigations:[{title:"Map and time evidence board",question:"What can maps, dates, and sources tell us about two communities?",steps:["Mark Falmouth, Massachusetts, and Redding, California; label both oceans and draw the route west.","Add a key and solve a fictional inset scale problem.","Arrange six project or move events chronologically.","Inspect two parent-provided dated sources and write I notice… / This may suggest…"],checks:[["map-time-board","I completed the map, timeline, and two-source observation."]],fields:[{id:"journeyMap",label:"Describe or link my journey map and scale work",rows:3,required:true},{id:"timelineClue",label:"One before, after, or between timeline clue",rows:2,required:true},{id:"sourceObservation",label:"I notice…",rows:2,required:true},{id:"sourceInference",label:"This may suggest…",rows:2,required:true}]},{title:"Community connections board",question:"How do community life, place, and exchange connect?",steps:["Add one tradition that can move with people and one public service.","Add one constructive way a resident can raise a concern and finish: A legislature makes ___.","State that Indigenous communities existed before modern state borders and continue today; cite any specific community fact.","Connect a resource to a job and good/service; show a trade relationship."],checks:[["connections-board","I added culture, civics, Indigenous continuity, geography, and economics panels."]],fields:[{id:"civicPanel",label:"My community service, resident action, and legislature statement",rows:3,required:true},{id:"continuityPanel",label:"My Indigenous continuity statement and citation for any specific fact",rows:3,required:true},{id:"economicsPanel",label:"My resource chain and trade connection",rows:3,required:true}]}],
      assignment:{title:"Share the detective case",directions:["Give a three-to-five-minute presentation or recording.","Name a map clue, timeline clue, and strongest historical evidence.","Explain one thing communities do together.","Describe one idea you changed after checking evidence."],fields:[{id:"strongClaim",label:"I think ___ because Source ___ shows ___.",rows:3,required:true},{id:"presentationNotes",label:"My short presentation notes or recording link",rows:4,required:true},{id:"changedIdea",label:"One idea I changed after checking evidence",rows:3,required:true}]},
      exit:[{id:"check1",prompt:"What should you do when two accounts disagree?",type:"select",options:["Choose the most confident speaker","Compare relevant sources and evidence","Ignore every account"],required:true},{id:"check2",prompt:"Correct this statement: Indigenous communities are only from the past.",rows:2,required:true},{id:"check3",prompt:"How did one map, date, source, or measurement strengthen your final claim?",rows:3,required:true}],
      reviewSkills:["Integrating maps, timelines, and sources","Applying civic and economic ideas","Presenting an evidence-supported explanation"],portfolio:"Complete Community Detective case and short presentation record."
    }
  ]
};
