/* Add the seven History weeks to the existing portal without touching the History Baseline. */
(() => {
 'use strict';
 const S=window.HistoryStore,C=S.C;let changed=false;
 try{
  for(const w of C.weeks){let task=data.assignments.find(x=>x.id===w.id);if(!task){data.assignments.push({id:w.id,title:'History Week '+w.week+' · '+w.title,subject:'History–Social Science',due:'',description:w.subtitle+'. '+w.assignment.title+'.',link:'history.html?id='+w.id,complete:false,completedDate:'',historyWeek:w.week});changed=true;}else{if(task.subject!=='History–Social Science'){task.subject='History–Social Science';changed=true;}if(!task.historyWeek){task.historyWeek=w.week;changed=true;}if(!task.link){task.link='history.html?id='+w.id;changed=true;}}}
  if(changed)saveData();S.syncPortal();data=S.read(S.recordKey,data);
  const filter=document.createElement('select');filter.id='historyWeekFilter';filter.setAttribute('aria-label','History week');filter.innerHTML='<option value="all">History: all weeks</option>'+C.weeks.map(w=>`<option value="${w.week}">History week ${w.week}: ${S.esc(w.title)}</option>`).join('');document.querySelector('#assignments .filter-row').append(filter);
  const banner=document.createElement('section');banner.className='panel history-assignment-banner';banner.innerHTML='<h3>Community Explorer · Seven-week Grade 3 course</h3><p>Build from Rory’s completed History Baseline with maps, timelines, sources, community problems, and evidence-based explanations.</p><div class="actions"><a href="history.html">Open all seven History weeks</a><a href="parent.html#history-parent">Parent plan and review</a></div>';document.querySelector('#assignments .filter-row').before(banner);
  const previous=renderAssignments;
  renderAssignments=function(){
   const ela=document.getElementById('elaWeekFilter');if(subjectFilter.value==='History–Social Science'&&ela)ela.value='all';if(subjectFilter.value==='English Language Arts')filter.value='all';
   previous();const showHistory=subjectFilter.value==='all'||subjectFilter.value==='History–Social Science';banner.hidden=!showHistory;filter.hidden=!showHistory;
   for(const card of [...assignmentList.querySelectorAll('[data-assignment-id]')]){const task=data.assignments.find(x=>x.id===card.dataset.assignmentId);if(!task)continue;if(filter.value!=='all'&&subjectFilter.value==='History–Social Science'&&task.historyWeek!==Number(filter.value)){card.remove();continue;}if(!task.historyWeek)continue;card.dataset.historyId=task.id;const w=C.weeks.find(x=>x.id===task.id),meta=document.createElement('p');meta.className='meta';meta.textContent='Week '+w.week+' · '+w.scope+' · Evidence checkpoint and parent review';card.querySelector('h3').after(meta);card.querySelectorAll('.actions button').forEach(button=>button.remove());const link=card.querySelector('.actions a');if(link){link.textContent='Open History week';link.removeAttribute('target');}}
   if(!assignmentList.children.length)assignmentList.innerHTML='<p class="empty">No assignments match these filters.</p>';
  };
  filter.onchange=()=>{if(filter.value!=='all'){subjectFilter.value='History–Social Science';const ela=document.getElementById('elaWeekFilter');if(ela)ela.value='all';const science=document.getElementById('scienceWeekFilter');if(science)science.value='all';}renderAssignments();};
  const ela=document.getElementById('elaWeekFilter');if(ela)ela.addEventListener('change',()=>{if(ela.value!=='all')filter.value='all';renderAssignments();});
  subjectFilter.onchange=()=>{const ela=document.getElementById('elaWeekFilter'),science=document.getElementById('scienceWeekFilter');if(subjectFilter.value!=='English Language Arts'&&ela)ela.value='all';if(subjectFilter.value!=='Science'&&science)science.value='all';if(subjectFilter.value!=='History–Social Science')filter.value='all';renderAssignments();};statusFilter.onchange=renderAssignments;
  const report=document.createElement('article');report.className='panel';report.innerHTML='<h3>Seven-week History record</h3><p>Investigation data, evidence-based explanations, saved checkpoints, assistance, portfolio samples, and parent review.</p><a href="parent.html#history-parent">Open History teaching records</a>';document.querySelector('#reports .report-grid').append(report);
  renderAll();if(location.hash==='#history'){setView('assignments');subjectFilter.value='History–Social Science';renderAssignments();}
 }catch(error){const message=document.createElement('p');message.className='history-alert';message.setAttribute('role','alert');message.textContent='History course needs attention: '+error.message;document.getElementById('assignments').prepend(message);}
})();
