/* Seven-week Grade 3 Science instructional bridge. Baseline data is never read or changed here. */
window.SCIENCE_COURSE={
 version:'2026.1',schoolYear:'2026–2027',student:'Rory',grade:3,
 title:'Rory’s Seven-Week Science Lab',
 opening:'Your Science Baseline is complete. Now you are beginning seven weeks of new Grade 3 science. You already showed that you know a lot about living things, Earth science, weather records, fossils, and some forces. In this course, you will investigate, build, measure, draw models, and use evidence to explain what happens.',
 routine:['OBSERVE','RECORD DATA','CHOOSE EVIDENCE','MAKE A CLAIM'],
 sources:[
  {title:'California NGSS Grade Three arranged by DCI',url:'https://www.cde.ca.gov/ci/pl/documents/cangssgr3-dci.pdf'},
  {title:'California Content Standards — Science',url:'https://www2.cde.ca.gov/cacs/science'},
  {title:'NGSS Grade 3 standards',url:'https://www.nextgenscience.org/search-standards?keys=&tid%5B%5D=103&tid_4%5B%5D=40'}
 ],
 weeks:[
  {
   id:'science3-w1',week:1,title:'Thinking Like a Scientist',subtitle:'Observation, inference, evidence, and data',scope:'Build a reasoning habit we will use every week.',visual:'evidence',standards:['SEP-3','SEP-4','SEP-6','SEP-7'],
   baselineNote:'Uses observation, data-reading, and evidence questions as a starting point. This is focused practice, not a repeat of the full baseline.',
   lesson:[
    'Scientists pay close attention to what actually happens. An observation is something you see, hear, feel, count, or measure. An inference is an idea about why it happened. A prediction tells what you think may happen next. An opinion tells what someone likes or believes.',
    'Data are observations that you record. Evidence is the part of the data that helps answer your question. After you collect evidence, you can make a claim. Try: “I observed…” “My data show…” “This is evidence because…” “Therefore, I claim…”'
   ],
   vocabulary:[['Observation','Something directly noticed or measured.'],['Inference','An explanation based on observations.'],['Prediction','What you think may happen next.'],['Opinion','What someone thinks or prefers.'],['Data','Recorded observations or measurements.'],['Evidence','Data that help answer a question.'],['Claim','An answer supported by evidence.'],['Fair test','A test in which most things stay the same.']],
   prep:{label:'PARENT-LED INVESTIGATION',materials:['Two identical sheets of paper','A ruler or tape to mark one release height','A clear floor space'],note:'An adult releases the papers together while Rory watches and records. Keep paper size, height, and release method as similar as possible.'},
   investigations:[{title:'Flat paper or crumpled paper?',question:'Does paper shape affect which sheet reaches the floor first?',steps:['Leave one sheet flat and crumple the other.','Predict which will land first.','Release both from the same marked height for four trials. Alternate their left/right positions.','Record only what happened: flat first, crumpled first, or together.'],checks:[['paper-test','We completed four fair trials.']],fields:[
    {id:'prediction',label:'My prediction before testing',rows:2,required:true},
    {id:'trial1',label:'Trial 1 result',type:'select',options:['Flat first','Crumpled first','Together'],required:true},{id:'trial2',label:'Trial 2 result',type:'select',options:['Flat first','Crumpled first','Together'],required:true},{id:'trial3',label:'Trial 3 result',type:'select',options:['Flat first','Crumpled first','Together'],required:true},{id:'trial4',label:'Trial 4 result',type:'select',options:['Flat first','Crumpled first','Together'],required:true}
   ]}],
   assignment:{title:'My scientist report',directions:['Count the outcome of all four trials.','Choose the result or pattern that answers the test question.','Make a claim that matches the results, even if it differs from your prediction.'],fields:[
    {id:'outcomeCount',label:'What pattern do the four trials show?',rows:2,required:true},{id:'evidence',label:'Which recorded result best supports your claim? Why is it evidence?',rows:3,required:true},{id:'claim',label:'My claim about which paper shape usually landed first',rows:3,required:true},{id:'notEvidence',label:'Why is “the crumpled paper wanted to win” not scientific evidence?',rows:2,required:true}
   ]},
   exit:[{id:'check1',prompt:'Which statement is a direct observation?',type:'select',options:['The leaf is green.','The leaf is healthy.','The leaf will turn brown.'],required:true},{id:'check2',prompt:'A table says the crumpled paper landed first in 3 of 4 trials. Which evidence is relevant?',type:'select',options:['I liked the flat paper.','Crumpled paper was first in 3 trials.','I expected a tie.'],required:true},{id:'check3',prompt:'Why is a prediction made before testing not test data?',rows:2,required:true}],
   reviewSkills:['Direct observation versus inference, prediction, or opinion','Selecting data that support a claim'],portfolio:'Paper-drop data, a drawing or photo note, and an evidence-supported claim.'
  },
  {
   id:'science3-w2',week:2,title:'Materials and Changes',subtitle:'Properties, tests, and reversible changes',scope:'Reinforce selected prior-grade ideas through one useful design test.',visual:'materials',standards:['2-PS1-1 (reinforcement)','2-PS1-4 (reinforcement)','SEP-3','SEP-4'],
   baselineNote:'Focuses on flexible versus rigid, reading a material test, and using observations to classify changes.',
   lesson:[
    'Every material has properties we can observe or test. A rubber band is flexible. A craft stick is more rigid. A towel may absorb water, while plastic may keep water out. Scientists test properties before deciding which material is best for a job.',
    'Some changes are reversible: the material can return to an earlier form, as water can freeze after ice melts. Other changes are irreversible: cooling or reshaping cannot easily return the object to its earlier form. We decide from observations, not from what we hoped would happen.'
   ],
   vocabulary:[['Material','What an object is made from.'],['Property','A feature that can be observed or tested.'],['Flexible','Bends easily without breaking.'],['Rigid','Does not bend easily.'],['Absorbent','Takes in liquid.'],['Water-resistant','Keeps most water from passing through.'],['Reversible change','A change that can be undone.'],['Irreversible change','A change that cannot easily be undone.']],
   prep:{label:'PARENT PREP + WATER SUPERVISION',materials:['Equal-size pieces of paper towel, cloth, foil, and plastic','Four dry tissues or cotton pads','Tray, water, and dropper or teaspoon','One ice cube in a clear cup','Paper and freezer access'],note:'Use the same number of drops and the same test setup for each material. An adult handles spills and later refreezes the melted water.'},
   investigations:[{title:'Material detective',question:'Which tested material would make the best small rain cover?',steps:['Place one material over a dry tissue.','Gently test whether it bends.','Add the same number of water drops to each material.','Record how many drops reach the tissue and whether the material absorbs water.'],checks:[['material-test','We tested all four materials with equal drops.']],fields:[
    {id:'paperData',label:'Paper towel — bend and water observations',rows:2,required:true},{id:'clothData',label:'Cloth — bend and water observations',rows:2,required:true},{id:'foilData',label:'Foil — bend and water observations',rows:2,required:true},{id:'plasticData',label:'Plastic — bend and water observations',rows:2,required:true}
   ]},{title:'Can the change be reversed?',question:'Which changes can return to an earlier form?',steps:['Observe an ice cube melt in a clear cup.','Have an adult refreeze the water later.','Tear a separate sheet of paper and try to return it to one unbroken sheet.','Record what happened instead of what you expected.'],checks:[['change-test','We observed melting/refreezing and tearing.']],fields:[{id:'iceObservation',label:'What did you directly observe about the ice and water?',rows:2,required:true},{id:'paperObservation',label:'What did you directly observe about the torn paper?',rows:2,required:true}]}],
   assignment:{title:'Design a tiny rain cover',directions:['Choose one tested material.','Draw or describe a small cover.','Name the properties that matter.','Use two test results as evidence.'],fields:[{id:'chosenMaterial',label:'Material I chose and the properties that make it useful',rows:3,required:true},{id:'coverEvidence',label:'Two test results that support my choice',rows:3,required:true},{id:'changeClaim',label:'Which change was reversible and which was irreversible? Use an observation for each.',rows:3,required:true}]},
   exit:[{id:'check1',prompt:'Which word describes a rubber band that bends easily?',type:'select',options:['Flexible','Rigid','Absorbent'],required:true},{id:'check2',prompt:'Material A let through 0 drops; B let through 3; C let through 7. Which kept out the most water?',type:'select',options:['Material A','Material B','Material C'],required:true},{id:'check3',prompt:'Which tested observation shows a change could be reversed?',rows:2,required:true}],
   reviewSkills:['Observable material properties','Reading simple experimental data','Reversible and irreversible changes'],portfolio:'Material-properties record, rain-cover plan, and supported choice.'
  },
  {
   id:'science3-w3',week:3,title:'Forces and Motion',subtitle:'Pushes, pulls, balance, patterns, and magnets',scope:'Briefly reinforce push/pull, then begin new Grade 3 forces learning.',visual:'forces',standards:['3-PS2-1','3-PS2-2','3-PS2-3'],
   baselineNote:'Balanced forces are new Grade 3 instruction. Rory’s correct magnet response becomes a deeper distance investigation.',
   lesson:[
    'A force is a push or pull on an object. Forces have directions. When equal forces act in opposite directions, they are balanced and do not change an object’s motion. When forces are unbalanced, an object may start, stop, speed up, slow down, or change direction.',
    'Some forces act across a space. You already noticed that a magnet can move a paper clip without touching it. Now you will test how distance changes that interaction and use repeated motion data to find a pattern.'
   ],
   vocabulary:[['Force','A push or pull.'],['Motion','A change in position.'],['Direction','The way an object moves or a force acts.'],['Balanced forces','Forces that do not change motion.'],['Unbalanced forces','Forces that change motion.'],['Magnetic force','A push or pull caused by magnets.'],['Contact','Touching.'],['Pattern','Something that repeats in a predictable way.']],
   prep:{label:'PARENT PARTNER + SMALL-PARTS SUPERVISION',materials:['Light box or toy cart with string on two sides','Floor start line','Toy car, simple ramp, and ruler','Magnet, paper clips or steel washers','Index cards or paper layers'],note:'An adult partners in the pull test and supervises all small metal pieces. Use the same car and ramp start position in every motion trial.'},
   investigations:[{title:'Balanced and unbalanced pulls',question:'What happens when opposite pulls are equal or unequal?',steps:['Put the box on the start line.','Pull equally in opposite directions and observe.','Try a stronger pull on one side, then on the other.','Draw arrows or describe direction and strength.'],checks:[['force-test','We tested equal and unequal opposite pulls.']],fields:[{id:'equalPull',label:'Equal opposite pulls — what did the box do?',rows:2,required:true},{id:'leftPull',label:'Stronger pull to the left — what did the box do?',rows:2,required:true},{id:'rightPull',label:'Stronger pull to the right — what did the box do?',rows:2,required:true}]},{title:'Motion pattern and magnet gap',question:'Can repeated observations reveal a pattern? Can a magnet act across a gap?',steps:['Release the same car from the same ramp mark three times. Measure its stopping distance.','Predict the fourth result from the pattern.','Add paper layers between a magnet and paper clip.','Record the greatest tested number of layers at which the clip still moved.'],checks:[['motion-test','We completed three equal-start car trials.'],['magnet-test','We tested a magnet across at least one visible gap.']],fields:[{id:'car1',label:'Car trial 1 stopping distance',required:true},{id:'car2',label:'Car trial 2 stopping distance',required:true},{id:'car3',label:'Car trial 3 stopping distance',required:true},{id:'carPrediction',label:'My fourth-trial prediction based on the pattern',rows:2,required:true},{id:'magnetLayers',label:'Greatest tested gap or paper-layer count that still moved the clip',required:true}]}],
   assignment:{title:'Explain the forces',directions:['Draw force arrows on paper for the equal and unequal tests.','Describe which trial had balanced forces.','Use the magnet result to make an evidence-based claim.'],fields:[{id:'forceDrawing',label:'Describe or link my force-arrow drawing',rows:3,required:true},{id:'balanceClaim',label:'Which test had balanced forces? Use the object’s motion as evidence.',rows:3,required:true},{id:'magnetClaim',label:'Does the test support the claim that magnetic force can act without contact? Cite the gap data.',rows:3,required:true}]},
   exit:[{id:'check1',prompt:'Drawing a wagon toward you with its handle is a…',type:'select',options:['Pull','Push','Balanced force'],required:true},{id:'check2',prompt:'Equal opposite forces act on a box and its motion does not change. The forces are…',type:'select',options:['Balanced','Magnetic','A prediction'],required:true},{id:'check3',prompt:'What observation showed magnetic force acting across a gap?',rows:2,required:true}],
   reviewSkills:['Push versus pull','Balanced and unbalanced forces','Motion patterns','Magnetic forces without contact'],portfolio:'Force arrows, motion measurements, magnet-gap data, and claims.'
  },
  {
   id:'science3-w4',week:4,title:'Life Cycles',subtitle:'Models, stages, and shared patterns',scope:'New Grade 3 instruction.',visual:'cycles',standards:['3-LS1-1'],
   baselineNote:'Life-cycle modeling is upcoming Grade 3 learning, not a deficit.',
   lesson:[
    'Every kind of organism has a life cycle. Different organisms can have very different stages, but their cycles share a pattern: organisms begin life, grow, become able to reproduce, and eventually die. Their offspring begin a new cycle.',
    'A model helps us show stages and their order. Arrows matter because they show what happens next and how a new generation continues the cycle. A model represents important ideas, but it is not the real organism.'
   ],
   vocabulary:[['Organism','A living thing.'],['Life cycle','The stages of an organism’s life.'],['Stage','One part of a life cycle.'],['Offspring','A new organism produced by a parent.'],['Reproduce','Produce offspring.'],['Model','A representation used to explain an idea.'],['Pattern','An order or relationship that repeats.'],['Metamorphosis','A major change in body form during a life cycle.']],
   prep:{label:'PARENT PREP',materials:['Paper plate or cardstock','Child-safe scissors, fastener or tape, and crayons','Three or four bean seeds if available','Damp paper towel or planting cup'],note:'An adult helps with the fastener and prepares the seeds. If four seedlings are not available, use one seedling for repeated observations or use a dated parent-provided growth record; label which kind of evidence you used.'},
   investigations:[{title:'Build two life-cycle models',question:'How are the life cycles of a butterfly and flowering plant alike and different?',steps:['Put butterfly stages in order: egg, caterpillar, pupa, adult.','Draw a flowering plant cycle: seed, sprout, adult plant, flowers/new seeds.','Add arrows that show what happens next.','Start a bean-seed observation and draw only visible changes.'],checks:[['cycle-model','I made two circular models with arrows.'],['seed-start','We started and dated a bean-seed observation.']],fields:[{id:'butterflyOrder',label:'Butterfly stages in order',rows:2,required:true},{id:'plantOrder',label:'Flowering plant stages in order',rows:2,required:true},{id:'seedFirst',label:'First dated seed observation',rows:2,required:true},{id:'seedLater',label:'Later seed observation (return when ready)',rows:2,required:true}]}],
   assignment:{title:'Compare the cycles',directions:['Use “Both…” to name a shared pattern.','Use “But…” to name a difference.','Explain why arrows make the model useful.'],fields:[{id:'bothBut',label:'Both life cycles…, but…',rows:3,required:true},{id:'arrowPurpose',label:'What do the arrows help a reader understand?',rows:2,required:true},{id:'modelLimit',label:'What can your model show, and what can it not show?',rows:3,required:true}]},
   exit:[{id:'check1',prompt:'Choose the butterfly stages in order.',type:'select',options:['Egg → caterpillar → pupa → adult','Adult → pupa → egg → caterpillar','Pupa → egg → adult → caterpillar'],required:true},{id:'check2',prompt:'Why do life-cycle models use arrows?',rows:2,required:true},{id:'check3',prompt:'What broad pattern do plant and animal life cycles share?',rows:2,required:true}],
   reviewSkills:['Life-cycle sequence','Using and explaining a model','Finding a shared pattern'],portfolio:'Two life-cycle models, seed observation, and comparison.'
  },
  {
   id:'science3-w5',week:5,title:'Traits',subtitle:'Inherited, learned, and influenced by environment',scope:'New Grade 3 instruction.',visual:'traits',standards:['3-LS3-1','3-LS3-2','3-LS4-3'],
   baselineNote:'Inherited traits and environmental effects are upcoming Grade 3 learning. Results that differ from a prediction are still useful data.',
   lesson:[
    'A trait is a characteristic of an organism. Some traits are inherited from parents. Offspring are similar to their parents, but they are not exact copies, so we see variation. Learned behaviors develop through experience or practice.',
    'Other characteristics can be affected by the environment, including water, light, food, temperature, and activity. Sometimes both inheritance and environment matter. Scientists need family information, observations, or test data before deciding what caused a difference.'
   ],
   vocabulary:[['Trait','A characteristic of an organism.'],['Inherited','Passed from parents to offspring.'],['Variation','Differences among organisms of the same kind.'],['Learned behavior','An action developed through experience.'],['Acquired characteristic','A characteristic developed during life.'],['Environment','Surrounding conditions that affect an organism.'],['Growth','Increase or change as an organism develops.'],['Survival','Continuing to live and meet needs.']],
   prep:{label:'PARENT-PLANNED MULTI-DAY TEST',materials:['Four similar seedlings if available','Labels and ruler','One steady light location','Measuring spoon and water'],note:'An adult chooses small, safe watering amounts. Keep seed type, container, light, and location the same. Use two seedlings per condition when possible.'},
   investigations:[{title:'Environment and growth',question:'Did water amount affect growth in this small test?',steps:['Measure each seedling before the test.','Give one group the regular planned water amount and the other group a smaller amount.','Measure both groups over several days.','Graph or draw the measurements. If the result is unclear, record that honestly.'],checks:[['growth-test','We used the planned watering amounts and recorded real measurements.']],fields:[{id:'groupAStart',label:'Group A starting measurement',required:true},{id:'groupBStart',label:'Group B starting measurement',required:true},{id:'groupAEnd',label:'Group A later measurement',required:true},{id:'groupBEnd',label:'Group B later measurement',required:true},{id:'growthPattern',label:'Pattern I see, or why the result is unclear',rows:3,required:true}]},{title:'Trait detective',question:'Which examples are inherited, learned, acquired, or influenced by environment?',steps:['Sort these nonhuman examples: natural fur color, a trained trick, muddy fur, plant height with different water, and differences among puppy siblings.','Explain one choice instead of relying only on the label.'],checks:[['trait-sort','I sorted and explained the trait examples.']],fields:[{id:'traitSort',label:'My trait sort and one explanation',rows:5,required:true}]}],
   assignment:{title:'Use the evidence honestly',directions:['Compare your measured plant groups.','Say whether the data support your prediction.','Use a habitat scenario to explain which organism could meet its needs.'],fields:[{id:'growthClaim',label:'My cautious claim about water and growth in this test',rows:3,required:true},{id:'growthEvidence',label:'Measurements that support—or do not clearly support—my claim',rows:3,required:true},{id:'habitatReasoning',label:'Choose an organism and habitat. What evidence shows it could survive well, less well, or not at all?',rows:4,required:true}]},
   exit:[{id:'check1',prompt:'Which is most likely inherited?',type:'select',options:['A puppy’s natural fur color','A dog’s trained trick','Mud on a dog’s fur'],required:true},{id:'check2',prompt:'Which is learned?',type:'select',options:['A trained trick','Natural eye color','The number of legs'],required:true},{id:'check3',prompt:'Did your measured results support your prediction? Use the numbers.',rows:2,required:true}],
   reviewSkills:['Inherited versus learned or acquired characteristics','Environmental effects on growth','Matching claims to measurements'],portfolio:'Growth graph or drawing, trait sort, and honest conclusion.'
  },
  {
   id:'science3-w6',week:6,title:'Earth Science Through Evidence',subtitle:'Weather, climate, fossils, and limits of evidence',scope:'Apply demonstrated strengths to richer Grade 3 reasoning.',visual:'earth',standards:['3-ESS2-1','3-ESS2-2','3-LS4-1'],
   baselineNote:'Rory already compared weather records and used fossils as evidence. This week extends those strengths instead of repeating simple identification.',
   lesson:[
    'Weather describes what the air and sky are like at a particular time. Climate describes patterns of weather in a place across many years. Scientists record temperature, rain, wind, and other weather data. A few days of weather cannot prove a climate pattern.',
    'Fossils are evidence of organisms and environments from long ago. Fossil evidence can support some claims, but it cannot answer every question. A fossil leaf can tell us that a plant lived long ago; by itself, it cannot tell us tomorrow’s weather or an exact date.'
   ],
   vocabulary:[['Weather','Atmospheric conditions at a particular time and place.'],['Climate','The usual range and pattern of weather over many years.'],['Temperature','How hot or cold something is.'],['Precipitation','Water falling from the sky.'],['Graph','A visual display of data.'],['Fossil','Preserved evidence of past life.'],['Environment','Conditions and surroundings where organisms live.'],['Limitation','Something the available evidence cannot show.']],
   prep:{label:'PARENT OUTDOOR CHECK',materials:['Outdoor-safe thermometer if available','Paper wind streamer','Paper and ruler','Optional clay or play dough and a leaf or shell'],note:'Observe outdoors with an adult. The supplied seasonal numbers are fictional practice data; they are not a local weather record. A clay imprint is a model, not a real fossil.'},
   investigations:[{title:'Short weather record',question:'What can a few days of weather show, and what can they not prove?',steps:['Record temperature or hot/warm/cool/cold, sky, precipitation, and wind for three observations.','Keep these observations separate from a long-term climate claim.'],checks:[['weather-record','I recorded three actual weather observations or used three parent-provided observations.']],fields:[{id:'weather1',label:'Weather observation 1',rows:2,required:true},{id:'weather2',label:'Weather observation 2',rows:2,required:true},{id:'weather3',label:'Weather observation 3',rows:2,required:true}]},{title:'Seasonal data and fossil model',question:'What patterns and past-life claims does the evidence support?',steps:['Use this multi-year sample: winter rainy days 42, spring 28, summer 6, fall 19. Make a bar graph or pictograph.','Make an optional clay imprint and label it “model.”','Imagine a fossil leaf in old rock. Identify what it supports and what it cannot prove.'],checks:[['weather-graph','I made or described a graph using all four values.']],fields:[{id:'graphNote',label:'Describe or link my graph. What seasonal pattern does it show?',rows:3,required:true},{id:'fossilModel',label:'Describe my fossil model or evidence drawing',rows:2,required:true}]}],
   assignment:{title:'Claims with boundaries',directions:['Make one claim supported by the weather numbers.','Make a separate prediction and label it as a prediction.','Explain what a fossil leaf supports and one thing it does not prove.'],fields:[{id:'weatherClaim',label:'Weather-data claim with exact numbers',rows:3,required:true},{id:'weatherPrediction',label:'My labeled prediction',rows:2,required:true},{id:'fossilSupport',label:'What a fossil leaf can support',rows:2,required:true},{id:'fossilLimit',label:'What that fossil alone cannot prove',rows:2,required:true}]},
   exit:[{id:'check1',prompt:'Which describes conditions today?',type:'select',options:['Weather','Climate','A fossil'],required:true},{id:'check2',prompt:'Which claim can a fossil leaf support?',type:'select',options:['A plant lived long ago.','Tomorrow will be rainy.','The rock has an exact age without another test.'],required:true},{id:'check3',prompt:'Which exact seasonal values support your weather claim?',rows:2,required:true}],
   reviewSkills:['Weather data versus climate patterns','Using fossils as evidence','Naming limits of available evidence'],portfolio:'Weather graph and fossil-evidence explanation.'
  },
  {
   id:'science3-w7',week:7,title:'Engineering Design',subtitle:'Science integration project',scope:'Apply Science ideas in a build–test–improve challenge.',visual:'engineering',standards:['3-ESS3-1','3-5-ETS1-1','3-5-ETS1-2','3-5-ETS1-3'],
   baselineNote:'Rory already selected a flood-reduction solution. Now he will plan, build, test, compare, and improve his own model.',
   lesson:[
    'Engineers solve problems by defining what a successful solution must do. Criteria are the things it must accomplish. Constraints are limits on materials, time, size, or cost.',
    'A plan or model shows how an idea might work. It does not prove the design will work. Engineers build and test solutions, record results, compare data, and improve the design. The best-looking design is not automatically the best solution. Test evidence decides.'
   ],
   vocabulary:[['Engineer','A person who designs solutions.'],['Criteria','What a successful design must do.'],['Constraint','A limit on a design.'],['Plan','A drawing or description made before building.'],['Prototype','A version used to test an idea.'],['Fair test','A comparison with the same test conditions.'],['Failure point','The place where a design does not work.'],['Redesign','Improve a design using test evidence.']],
   prep:{label:'PARENT-LED WATER TEST + SPILL SUPERVISION',materials:['Shallow tray and small paper house or block','Dry tissue under the house','Measuring cup and water','Index cards, foil, straws or craft sticks, tape, modeling clay','Ruler, towel, and child-safe scissors'],note:'An adult controls each equal water pour. Suggested criteria: house stays upright and in place; no more than one tissue corner gets wet. Suggested constraints: no more than three material types and 30 cm of tape.'},
   investigations:[{title:'Protect a home from model floodwater',question:'Which design meets the criteria better under the same test?',steps:['Write the criteria and constraints.','Draw and label Design A before building.','Test Design A twice with the same water amount, pour point, and tray setup.','Identify a failure point and plan one evidence-based improvement.','Build Design B and repeat the same two tests.'],checks:[['plan-made','I drew and labeled a plan before building.'],['design-a-tested','We tested Design A twice.'],['design-b-tested','We tested improved Design B twice under the same conditions.']],fields:[{id:'criteria',label:'Our success criteria',rows:2,required:true},{id:'constraints',label:'Our material, size, time, or cost limits',rows:2,required:true},{id:'planA',label:'Describe or link my labeled Design A plan',rows:3,required:true},{id:'a1',label:'Design A test 1 — wet corners, house movement, observations',rows:2,required:true},{id:'a2',label:'Design A test 2 — wet corners, house movement, observations',rows:2,required:true},{id:'failure',label:'Failure point and the result that revealed it',rows:2,required:true},{id:'improvement',label:'What I changed for Design B and why',rows:3,required:true},{id:'b1',label:'Design B test 1 — wet corners, house movement, observations',rows:2,required:true},{id:'b2',label:'Design B test 2 — wet corners, house movement, observations',rows:2,required:true}]}],
   assignment:{title:'Engineering notebook conclusion',directions:['Compare both designs using the criteria.','Name material-property, force, or water-flow ideas you used.','Choose the stronger solution from test evidence, not appearance or preference.'],fields:[{id:'scienceIdeas',label:'Science ideas I used in the design',rows:3,required:true},{id:'betterDesign',label:'My claim: which design met the criteria better?',rows:2,required:true},{id:'designEvidence',label:'At least two test results that support my claim',rows:4,required:true},{id:'nextChange',label:'One next improvement I would test',rows:2,required:true}]},
   exit:[{id:'check1',prompt:'Why can a plan not prove a design will work?',rows:2,required:true},{id:'check2',prompt:'Name one criterion and one constraint from this challenge.',rows:2,required:true},{id:'check3',prompt:'Which design worked better, and which data—not preference—show that?',rows:3,required:true}],
   reviewSkills:['Purpose of plans and models','Criteria and constraints','Comparing solutions from fair-test results'],portfolio:'Plan, criteria, test table, drawings or photos, redesign notes, and final claim.'
  }
 ]
};
