const {chromium}=require('playwright');
const fs=require('fs'),assert=require('assert'),path=require('path');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const results=[];
for(const student of ['Brody','Rory']){
 const c=await b.newContext({acceptDownloads:true}),p=await c.newPage(),base=(process.env.HOMESCHOOL_QA_URL||'http://127.0.0.1:8765/')+student+'s-Homeschool/',prefix=student.toLowerCase(),recordKey=student==='Brody'?'brodyHomeschoolRecordV1':'roryHomeschoolRecordV2';p.on('dialog',d=>d.accept());
 await p.goto(base);await p.getByRole('button',{name:'+ Add Assignment'}).count();await p.getByRole('button',{name:'Assignments',exact:true}).click();await p.locator('#addAssignmentBtn').click();await p.locator('#assignmentTitle').fill('QA custom assignment');await p.locator('#assignmentForm button[type=submit]').click();assert(await p.getByRole('heading',{name:'QA custom assignment'}).isVisible());
 await p.getByRole('button',{name:'Daily Log',exact:true}).click();await p.locator('#logMinutes').fill('25');await p.locator('#logActivity').fill('QA independent work');await p.locator('#logForm button').click();
 await p.getByRole('button',{name:'Portfolio',exact:true}).click();await p.locator('#addPortfolioBtn').click();await p.locator('#portfolioTitle').fill('QA work sample');await p.locator('#portfolioDescription').fill('Written evidence');await p.locator('#portfolioForm button[type=submit]').click();await p.reload();
 const d=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),recordKey);assert(d.assignments.some(a=>a.title==='QA custom assignment'));assert(d.logs.some(l=>l.minutes===25));assert(d.portfolio.some(w=>w.title==='QA work sample'));
 await p.goto(base+'diagnostic.html?subject=writing');await p.waitForSelector('#finish');await p.evaluate(prefix=>{let q={version:'2026.1',student:prefix==='brody'?'Brody':'Rory',subject:'writing',answers:{},index:24,startedAt:new Date().toISOString(),submittedAt:null};for(let i=1;i<=24;i++)q.answers['writing-'+i]={choice:4,exposure:'not-taught'};localStorage.setItem(prefix+'Baseline2026_writing',JSON.stringify(q));},prefix);await p.reload();await p.waitForSelector('#writing-response');await p.locator('#writing-response').fill('   ');await p.locator('#finish').click();assert((await p.locator('#validation').innerText()).includes('3 still'));
 for(let i=0;i<3;i++){await p.locator('#writing-unknown').check();if(i<2)await p.locator('#next').click();}await p.locator('#finish').click();await p.getByRole('heading',{name:'Assessment submitted'}).waitFor();
 const q=await c.newPage();await q.goto(base+'diagnostic.html?subject=reading');await q.waitForSelector('#finish');await p.goto(base+'diagnostic.html?subject=reading');await p.waitForSelector('#finish');
 await p.evaluate(prefix=>localStorage.setItem(prefix+'Baseline2026_reading',JSON.stringify({version:'2026.1',answers:{'reading-1':{choice:4}},index:0,submittedAt:new Date().toISOString()})),prefix);await q.getByRole('heading',{name:'Assessment submitted'}).waitFor();
 await p.goto(base+'parent.html');await p.locator('#parent-pass').fill('test-passphrase');await p.locator('#confirm-pass').fill('test-passphrase');await p.locator('#unlock button').click();await p.locator('#domains .parent-domain').first().waitFor();
 const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#export-all').click()]);const raw=fs.readFileSync(await dl.path(),'utf8'),exported=JSON.parse(raw);assert(exported.diagnosticReport.assessments.find(a=>a.subject==='writing').responses.slice(-3).every(r=>r.classification==='dont-know'));
 await p.locator('#restore-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(raw)});await p.waitForTimeout(100);assert.equal((await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).logs.length,recordKey)),d.logs.length);
 await p.goto(base);await p.evaluate(k=>localStorage.setItem(k,'{unreadable'),recordKey);await p.reload();assert(await p.getByRole('heading',{name:'Saved records need attention'}).isVisible());assert.equal(await p.evaluate(k=>localStorage.getItem(k),recordKey),'{unreadable');
 results.push(student+': assignment/log/portfolio persistence, blank writing blocked, explicit unknown writing accepted, cross-tab lock, backup merge and corrupt-record preservation');await c.close();
}
// Legacy currency-item ambiguity is credited; corrected new attempts retain exactly one key.
for(const legacy of [true,false]){const c=await b.newContext({acceptDownloads:true}),p=await c.newPage();await p.goto('http://127.0.0.1:8765/Rorys-Homeschool/');await p.evaluate(legacy=>{localStorage.setItem('rory_math_baseline_v1',JSON.stringify({answers:{28:'B'},index:27,submitted:true,submittedAt:new Date().toISOString(),...(legacy?{}:{itemVersion:2})}));},legacy);await p.goto('http://127.0.0.1:8765/Rorys-Homeschool/parent.html');await p.locator('#parent-pass').fill('test-passphrase');await p.locator('#confirm-pass').fill('test-passphrase');await p.locator('#unlock button').click();await p.locator('#domains .parent-domain').first().waitFor();const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#export-report').click()]);const r=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(r.assessments[0].responses[27].classification,legacy?'correct':'incorrect');await c.close();}
results.push('Rory legacy double-answer credit and corrected new-item scoring');await b.close();fs.writeFileSync(path.join(process.env.HOMESCHOOL_QA_ROOT||path.resolve(__dirname,'../..'),'qa-edge-results.json'),JSON.stringify(results,null,2));console.log(results.join('\n'));})().catch(e=>{console.error(e);process.exitCode=1});
